[project]
name = "agentic-ai-bootcamp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "divyat2605", email = "divya.tripathi.2605@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "langchain-groq>=1.1.3",
    "langchain-mcp-adapters>=0.3.2",
    "langgraph[cli]>=1.2.11",
    "mcp[cli]>=1.29.0",
]

[project.scripts]
agentic-ai-bootcamp = "agentic_ai_bootcamp:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
